#!/usr/bin/haserl  --upload-limit=32768 --shell=/bin/ash
<% echo -en "content-type: text/html\r\n\r\n" %>
<html>
<head>
  <title>Upgrading Firmware - Do not disconnect</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="refresh" content="140; URL=/index.html">
	<style type="text/css">
	@import url(/lib/configstyle.css); 
	</style>
</head>

<body>
  <div class="section">
    <div class="topbar">
      	<img src="/images/vtlogo.png" alt="Village Telco">
		<div class="titletext">	
		  <h1>VT SECN Configuration</h1>
		</div>
    </div>

	
	<h2> Upgrading firmware. Please wait for the timer to count down. </h2>

  <h2>Time remaining:	<span id="seconds">180</span>.</h2>
	<script>
	  var seconds = 180;
	  setInterval(
  	    function(){
              document.getElementById('seconds').innerHTML = --seconds;
            }, 1000
          );
	</script>

	<p></p>

	<h3>Writing vmlinux</h3>
	<% mtd write $FORM_vmlinux vmlinux.bin.l7  %>
	<h3>Writing root and then rebooting... wait for timer to count down.</h3>
	<% mtd -r write $FORM_root rootfs %>

  Return to: <a href="http://10.130.1.20/cgi-bin/secn-tabs"> VT SECN Configuration </a>
	
	</div>


</body>
</html> 
